name: Gif Comment
on: 
  issues:
    types: [opened]
    
jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout
      - name: Add funny comment
        uses: chan811/Lab5_PartyHorn
        id: GifComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_TOKEN: ${{ secrets.GIPHY_TOKEN }}
          comment_type: 'gif'
